sudo: falsesudo: false
language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7-dev"

before_install:
    - sudo apt-get update

install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install sklearn

script:
    - python setup.py install
    - cd examples
    - python iris.py

after_success:
    - codecov